import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.scss";
import Logo from "../assets/Atfor.png";
import { BsArrowRight } from "react-icons/bs";

export default function Home() {
  return (
    <>
      <Head>
        <title>Atfor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.circle} />
        <div className={styles.navbar}>
          <Image src={Logo} width={100} className={styles.logo} alt="app-logo" />
          <div className={styles.navLinks}>
            <Link href="/signup" className={styles.navLink}>
              Get started
            </Link>
            <Link href="/" className={styles.navLink}>
              Services
            </Link>
            <Link href="/" className={styles.navLink}>
              Contacts
            </Link>
          </div>
        </div>
        <div className={styles.description}>
          <div className={styles.title}>Atfor</div>
          <div className={styles.subTitle}>
            A Paperless Electronic Bill Management System
          </div>
          <button>
            <Link href="/signup">Get Started</Link>
            <BsArrowRight className={styles.icon} />
          </button>
        </div>
      </main>
    </>
  );
}
